# Groovy Eclipse formatter configuration
groovy.formatter.multiline.indentation=2
groovy.formatter.remove.unnecessary.semicolons=true
# Spock specific formatting
groovy.formatter.spock.where.table.align.pipe=true
groovy.formatter.spock.where.table.align.assignments=true
